services:
  dev:
    build: .
    container_name: dev
    volumes:
      - .:/workspace
    cap_add:
      - SYS_PTRACE # Required for debugging
    security_opt:
      - seccomp:unconfined # Required for debugging
    stdin_open: true
    tty: true
